### PR TITLE
refactor: prevent extra move for get-methods with nrvo

### PR DESCRIPTION
**Pull request by jirol9xa**
Motivation https://godbolt.org/z/jTd99xzf1

### CODE REVIEW

**Review by DeveloperPaul123 — CHANGES_REQUESTED** [review]
Thanks for the PR. If you could please address the build issues, that would be great.

**Comment by jirol9xa** [comment]
sorry, i am not able to compile it locally

**Comment by DeveloperPaul123** [comment]
Ok looks like some tests are failing. I'll have to investigate a bit more if you can't build it locally.

**Comment by jirol9xa** [comment]
I tried it on my home ubuntu 22.04 with gcc-11. Everything is fine, it is not possible to reproduce the crash.

**Comment by DeveloperPaul123** [comment]
@jirol9xa Unfortunately, this is the nature of something as low level as a thread pool. Even if it's no locally reproducible, it is still likely a bug somewhere. 

Were you able to run it with thread sanitizer enabled and/or asan?

**Comment by DeveloperPaul123** [comment]
I'll try this out later on on PopOS and Ubuntu 24.04 to see if it's reproducible.

**Comment by jirol9xa** [comment]
Tried to run with tsan, and had an error even if running from trunk =)) Pretty sure I am doing something wrong

**Comment by DeveloperPaul123** [comment]
Oh no, there might be a bug then. What error do you see?

**Comment by DeveloperPaul123** [comment]
> CMake Error at /home/voffk4/fast-thread-pool/build/_deps/doctest-src/scripts/cmake/doctestAddTests.cmake:45 (message): Error running test executable 'thread-pool/build/test/thread-pool-tests':
> 
> ```
> Result: 66
> Output: 
> ```

I was able to reproduce this. https://stackoverflow.com/questions/77850769/fatal-threadsanitizer-unexpected-memory-mapping-when-running-on-linux-kernels this stackoverflow helped me find a workaround. Setting ` sudo sysctl vm.mmap_rnd_bits=28` fixed the build issue for me, but I think TSan is giving false positives. I'll have to dig in a bit more. When I run the tests without TSan they all pass.

**Comment by DeveloperPaul123** [comment]
Welp, I re-ran the test and it passed this time :man_shrugging:

**Review by DeveloperPaul123 — APPROVED** [review]

**Pull request merged**
