### PR TITLE
Add CodeCov Support

### PR DESCRIPTION
**Pull request by DeveloperPaul123**
Attempts to add CodeCov support to the project.

References:

- https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake

### CODE REVIEW

**Comment by alugowski** [comment]
Just chanced across this. Appologies for unsolicited advice.

Code coverage reporting has to be built into the test binary and then uploaded to Codecov in the same Action.

So in your test/CMakeLists add something like this:

```cmake
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
        add_compile_options("--coverage")
        add_link_options("-lgcov" "--coverage")
    endif()
```

Then in your Ubuntu tests run this after you run your GCC test:

```yml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_include: include/*
```

**Comment by DeveloperPaul123** [comment]
@alugowski Thanks for the tips! I'll have to give this a try

**Comment by DeveloperPaul123** [comment]
I haven't been able to get this to work. When building with GCC 11 on my WSL instance of Ubuntu, the flags have no effect and test coverage info/data is not created.

**Comment by alugowski** [comment]
This run looks like it worked: https://github.com/DeveloperPaul123/thread-pool/actions/runs/5033381080/jobs/9027568826

Tho this:
```
[2023-05-20T17:35:35.941Z] ['info'] -> No token specified or token is empty
```

implies the `CODECOV_TOKEN` repo secret isn't set.

**Comment by DeveloperPaul123** [comment]
@alugowski Yes the run succeeded, but the coverage report states that 0% of the code is covered. Even when I try things locally, the generated code coverage report is 0%. I think it has something to do with my library being header only and possibly a templated class, but I still haven't fully figured things out.

**Comment by DeveloperPaul123** [comment]
Regarding the token, it seems that the token secret is not required for public repositories anymore.

**Comment by alugowski** [comment]
I just did a new repo a few days ago and codecov showed 0 lines covered
until I set the token. But you’re right, everything else worked right away
without the token.

**Comment by DeveloperPaul123** [comment]
I have set the token as well with the same results. Did you just create a secret variable for actions in the repo?

**Comment by alugowski** [comment]
Yeah.
Screenshot 2023-05-22 at 11 21 18 AM

The branch has changed since that run. It now has an include filter for a file that is not in the repo, so it'll obviously report nothing.

**Comment by DeveloperPaul123** [comment]
I reverted to using `include/*` and it still reports 0%. There must be something I'm missing or just don't understand.

**Comment by DeveloperPaul123** [comment]
Last run seems to have worked. Thanks to [tcbrindle/flux](https://github.com/tcbrindle/flux) for a [reference](https://github.com/tcbrindle/flux/blob/main/.github/workflows/codecov.yml)

**Pull request merged**
